### ISSUE TITLE
OTRS 6 - Error on CustomerTicketMessage - Cannot read property 'Get' of undefined

### ISSUE THREAD

**Issue by meisterheister** [znuny/Znuny4OTRS-AutoSelect#3]
This issue came up after upgrading from OTRS 5 to 6 (6.0.4 currently). When logging in to the customer interface and click "New Ticket" (/otrs/customer.pl?Action=CustomerTicketMessage) the default RichText Editor (ckeditor 4.7.0) will not load.

Error in Browser Console (Opera 50.0):
![image](https://user-images.githubusercontent.com/35762852/35325122-1abe1c96-00f3-11e8-8228-9b394ca262ce.png)

**Comment by jepf** [comment]
@meisterheister 
Thank you for reporting this issue. The problem was a missing Javascript file in package Znun4OTRS-Repo. Please update this package to version 6.0.13.
