### ISSUE TITLE
Internal Server Error 500 - Can't locate object method "AddJSOnDocumentCompleteIfNotExists"

### ISSUE THREAD

**Issue by meisterheister** [znuny/Znuny4OTRS-AutoSelect#4]
After Updating Znuny-Repo as suggested for Issue 3 (https://github.com/znuny/Znuny4OTRS-AutoSelect/issues/3) all Agent and Customer views are generating an internal server error.

Apache log is showing the following error:
`[Thu Jan 25 09:24:38.424191 2018] [:error] [pid 18065] Can't locate object method "AddJSOnDocumentCompleteIfNotExists" via package "Kernel::Output::HTML::Layout" at /opt/otrs/Kernel/Output/HTML/FilterElementPost/Znuny4OTRSAutoSelect.pm line 62.\n`

**Comment by jepf** [comment]
@meisterheister 
I cannot reproduce this error, it works for me.
Can you please check if the package manager shows missing files for package Znuny4OTRS-Repo?
Do you have the file Kernel/Output/HTML/Layout/Znuny4OTRSRepo.pm in your OTRS directory?

**Comment by meisterheister** [comment]
Kernel/Output/HTML/Layout/Znuny4OTRSRepo.pm was there, however I was able to fix the issue by Reinstalling the Znuny4OTRS-Repo package.

Issue closed.
