### ISSUE TITLE
AutoSelect issue with SLA related to Service Selection using OTRS 6.0.15

### ISSUE THREAD

**Issue by RegularEmployee** [znuny/Znuny4OTRS-AutoSelect#5]
When a customer creates a new ticket, the automatic selection of SLA and Service doesn't work anymore.  The logged-in user has assigned the service "Standard Support". The service itself has one assigned SLA "Standard SLA". In a previous version both had therefore been selected automatically and could be hidden. 

Upon opening "/otrs/customer.pl?Action=CustomerTicketMessage" the form looks like this:
![image](https://user-images.githubusercontent.com/13982879/51185849-841ce700-18d8-11e9-93c9-be9c4369bc30.png) 
Now the Service "Standard Support" ist selected automatically (and could be hidden), nothing can be selected in the SLA drop down. It seeems that the dependency to the SLA is no longer recognized. 
When selecting the Service again (with double click) suddenly the SLA gets populated and teh "Standard SLA" is selected.  

![image](https://user-images.githubusercontent.com/13982879/51186374-c561c680-18d9-11e9-8523-9c4e8885705a.png)

We tested this behaviour on several browsers. Here is a screen recording of Safari:
[screencast otrs autoselect.mp4.zip](https://github.com/znuny/Znuny4OTRS-AutoSelect/files/2760021/screencast.otrs.autoselect.mp4.zip)

**Comment by jepf** [comment]
Thank you @RegularEmployee for reporting the issue. We'll have a look.

**Comment by jepf** [comment]
@RegularEmployee 
Have you tried to enable SysConfig option **Znuny4OTRSAutoSelect###SelectAlways**? This should fix your problem.

**Comment by RegularEmployee** [comment]
@jepf 
Thank you for dealing with the issue so quickly. The above setting is enabled and this does not solve the problem. Are you using 6.0.15 of OTRS, we did not have the issue in previous versions.
![image](https://user-images.githubusercontent.com/13982879/51260182-04f9e280-19ae-11e9-92ca-3b4f0fdd1b22.png)
In our original version we had enabled Znuny4OTRSAutoSelect###SelectAlways and Znuny4OTRSAutoSelect###HideFields, so that the "normal" customer would see neither "Service" nor "SLA" drop-downs. When opening the page, Service was selected and hidden but SLA was still there and grey. My interpretation is, that the first field "Service" is set correctly, but somehow the selection is not "communicated" to the "SLA" field. This only happens, when "Service" is selected manually in the UI.

**Comment by RegularEmployee** [comment]
@jepf If you want, I could create an account on our system to reproduce the issue?

**Comment by RegularEmployee** [comment]
Here is a screenshot of how the ticket create (Action=CustomerTicketMessage) form looks like when "SelectAlways" and "HideFields" are activated. The service field is hidden and so should the SLA field, but it doesn't ... Somehow the relationship between ServiceID and SLAID is interrupted, as there is exactly one SLA for the Service defined.
![image](https://user-images.githubusercontent.com/13982879/51265098-3d9eb980-19b8-11e9-800f-43105d113473.png)
With this setting, customers are no longer able to create tickets. Therefore our work-around was to exclude the ServiceID from AutoSelect fields:
![image](https://user-images.githubusercontent.com/13982879/51265551-552a7200-19b9-11e9-9446-4094c3d3d17a.png)
Once the service is selected manually, the SLA disappears automatically, therefore it gets evaluated correcly. Very strange. Let me know what I can do to support you better ...

**Comment by jepf** [comment]
Thank you for the additional information. We'll look for a solution for this.

**Comment by jepf** [comment]
This issue should now be fixed with Znuny4OTRS-AutoSelect package version 6.0.5.

**Comment by RegularEmployee** [comment]
Wow that was fast! I'm looking forward to install and test it on our help desk. I suppose it will soon be available in Znuny4OTRS-Repo. Thanks a lot!

**Comment by RegularEmployee** [comment]
IHMO the ticket can be closed. I updated to version 6.0.5 this morning and the issue is fixed. Thank you for your fast reaction and solution.
